### ISSUE TITLE
self hosted server problems: Status.login: success.login => error.login.reason.account

### ISSUE THREAD

**Issue by jpjp** [mozilla/fxa-auth-server#965] opened 2015-06-11 18:26 UTC
I have a Linux box running the sync server behind mod_wsgi.
I can never add more than one device. As soon as I do, I get an error.
Unlinking/logging out/logging in again does not help.

from syncserver.ini:
`public_url = https://secure.example.com/ffsync/token/1.0/sync/1.5`

from the apache config:
```
WSGIProcessGroup mozsync
WSGIDaemonProcess mozsync user=mozsync group=mozsync processes=2 threads=25 python-path=/opt/mozilla/sync-1.5/syncserver/local/lib/python2.7/site-packages/
WSGIPassAuthorization On
WSGIScriptAlias /ffsync /opt/mozilla/sync-1.5/syncserver/syncserver.wsgi
```

client log:

```
1434046230813	Sync.LogManager	DEBUG	Flushing file log
1434046230813	Sync.LogManager	TRACE	Beginning stream copy to error-sync-1434046230813.txt: 1434046230813
1434046230815	Sync.Service	DEBUG	Exception: Login failed: error.login.reason.account No traceback available
1434046230815	Sync.Service	DEBUG	Not syncing: login returned false.
1434046230907	Sync.LogManager	TRACE	finished copy to: /home/user/.mozilla/firefox/what.default/weave/logs/error-sync-1434046230813.txt
1434046230907	Sync.LogManager	TRACE	onCopyComplete: 1434046230907
1434046230908	Sync.LogManager	TRACE	Scheduling cleanup.
1434046230908	Sync.LogManager	DEBUG	Log cleanup threshold time: 1433182230908
1434046231003	Sync.LogManager	DEBUG	Done deleting files.
1434046238724	Sync.Tracker.Clients	DEBUG	client.name preference changed
1434046238724	Sync.Tracker.Clients	WARN	Attempted to add undefined ID to tracker
1434046241313	FirefoxAccounts	DEBUG	setSignedInUser - aborting any existing flows
1434046241343	FirefoxAccounts	DEBUG	Notifying observers of fxaccounts:onlogin
1434046241343	Sync.BrowserIDManager	DEBUG	observed fxaccounts:onlogin
1434046241344	Sync.BrowserIDManager	INFO	Waiting for user to be verified.
1434046241344	FirefoxAccounts	DEBUG	already verified
1434046241345	Sync.BrowserIDManager	INFO	Starting fetch for key bundle.
1434046241346	FirefoxAccounts	DEBUG	already verified
1434046241346	Sync.BrowserIDManager	INFO	Fetching new keys
1434046241347	FirefoxAccounts	DEBUG	fetchKeys: true
1434046241579	Hawk	DEBUG	(Response) /account/keys: code: 200 - Status text: OK
1434046241580	Sync.RESTResponse	TRACE	Processing response headers.
1434046241581	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -580
1434046241584	FirefoxAccounts	DEBUG	Keys Obtained: kA=true, kB=true
1434046241639	FirefoxAccounts	DEBUG	Notifying observers of fxaccounts:onverified
1434046241646	Sync.BrowserIDManager	INFO	Getting an assertion from: https://secure.example.com/ffsync/token/1.0/sync/1.5
1434046241647	FirefoxAccounts	DEBUG	enter getAssertion()
1434046241676	FirefoxAccounts	DEBUG	got keyPair
1434046241677	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1434046241946	Hawk	DEBUG	(Response) /certificate/sign: code: 200 - Status text: OK
1434046241946	Sync.RESTResponse	TRACE	Processing response headers.
1434046241947	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -947
1434046241947	FirefoxAccounts	DEBUG	getCertificate got a new one: true
1434046241948	FirefoxAccounts	DEBUG	getAssertionFromCert
1434046241950	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1434046241951	Sync.BrowserIDManager	DEBUG	Getting a token
1434046241951	Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://secure.example.com/ffsync/token/1.0/sync/1.5
1434046242225	Common.TokenServerClient	DEBUG	Got token response: 200
1434046242225	Sync.RESTResponse	TRACE	Processing response headers.
1434046242226	Common.TokenServerClient	DEBUG	Successful token response
1434046242226	Sync.BrowserIDManager	DEBUG	Successfully got a sync token
1434046242228	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1434046242228	Sync.BrowserIDManager	INFO	Background fetch for key bundle done
1434046242228	Sync.Status	DEBUG	Status.login: error.login.reason.account => success.login
1434046242228	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1434046242228	Sync.BrowserIDManager	INFO	Doing initial sync actions
1434046242238	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1434046242256	Sync.Service	DEBUG	User-Agent: Firefox/38.0.5 FxSync/1.40.0.20150603135958.
1434046242256	Sync.Service	INFO	Starting sync at 2015-06-11 20:10:42
1434046242257	Sync.Service	DEBUG	In sync: should login.
1434046242258	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1434046242258	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1434046242259	Sync.Service	INFO	Logging in the user.
1434046242259	Sync.Service	DEBUG	Caching URLs under storage user base: https://secure.example.com/ffsync/token/1.0/sync/1.5/storage/1.5/2/
1434046242259	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1434046242260	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1434046242261	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1434046242291	Sync.Resource	DEBUG	mesg: GET fail 404 https://secure.example.com/ffsync/token/1.0/sync/1.5/storage/1.5/2/info/collections
1434046242291	Sync.Resource	DEBUG	GET fail 404 https://secure.example.com/ffsync/token/1.0/sync/1.5/storage/1.5/2/info/collections
1434046242292	Sync.BrowserIDManager	DEBUG	_findCluster found existing clusterURL, so discarding the current token
1434046242292	FirefoxAccounts	DEBUG	already verified
1434046242293	Sync.BrowserIDManager	INFO	Getting an assertion from: https://secure.example.com/ffsync/token/1.0/sync/1.5
1434046242293	FirefoxAccounts	DEBUG	enter getAssertion()
1434046242294	FirefoxAccounts	DEBUG	getKeyPair: already have a keyPair
1434046242294	FirefoxAccounts	DEBUG	 getCertificate already had one
1434046242294	FirefoxAccounts	DEBUG	getAssertionFromCert
1434046242297	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1434046242297	Sync.BrowserIDManager	DEBUG	Getting a token
1434046242298	Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://secure.example.com/ffsync/token/1.0/sync/1.5
1434046242536	Common.TokenServerClient	DEBUG	Got token response: 200
1434046242536	Sync.RESTResponse	TRACE	Processing response headers.
1434046242538	Common.TokenServerClient	DEBUG	Successful token response
1434046242538	Sync.BrowserIDManager	DEBUG	Successfully got a sync token
1434046242539	Sync.BrowserIDManager	DEBUG	_findCluster returning https://secure.example.com/ffsync/token/1.0/sync/1.5/storage/1.5/2/
1434046242539	Sync.Service	DEBUG	Cluster value = https://secure.example.com/ffsync/token/1.0/sync/1.5/storage/1.5/2/
1434046242539	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.account
1434046242539	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1434046242543	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
```

server log:

```
[Thu Jun 11 20:07:44.757462 2015] [:error] [pid 23478] INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: verifier.accounts.firefox.com
[Thu Jun 11 20:07:45.549941 2015] [:error] [pid 23478] INFO:mozsvc.metrics:{"tokenserver.backend.get_user": 0.0005459785461425781, "code": 200, "request_time": 0.7934908866882324, "remoteAddressChain": ["1.2.3.4"], "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0", "tokenserver.assertion.verify": 0.7919349670410156, "token.assertion.verify_success": 1, "path": "https://secure.example.com/ffsync/token/1.0/sync/1.5/token/1.0/sync/1.5", "method": "GET"}
[Thu Jun 11 20:07:45.589087 2015] [:error] [pid 23477] INFO:mozsvc.metrics:{"code": 404, "request_time": 0.00041294097900390625, "remoteAddressChain": ["1.2.3.4"], "agent": "Firefox/38.0.5 FxSync/1.40.0.20150525141253.desktop", "path": "https://secure.example.com/ffsync/token/1.0/sync/1.5/token/1.0/sync/1.5/storage/1.5/2/info/collections", "method": "GET"}
[Thu Jun 11 20:07:45.862062 2015] [:error] [pid 23478] INFO:mozsvc.metrics:{"tokenserver.backend.get_user": 0.0004050731658935547, "code": 200, "request_time": 0.1909019947052002, "remoteAddressChain": ["1.2.3.4"], "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0", "tokenserver.assertion.verify": 0.18958497047424316, "token.assertion.verify_success": 1, "path": "https://secure.example.com/ffsync/token/1.0/sync/1.5/token/1.0/sync/1.5", "method": "GET"}
```

What can I try next?

**Comment by rfk** [comment] 2015-07-03 00:15
> https://secure.example.com/ffsync/token/1.0/sync/1.5/token/1.0/sync/1.5/storage/1.5/2/info/collections

Sorry to leave this for so long.  There's something not right about this URL, I would expect it to be more like:

  https://secure.example.com/ffsync/storage/1.5/2/info/collections

This may be a configuration issue, can you post your config file with any secrets/passwords remove?
It might also be an issue with mod_wsgi re-writing the URL somehow, but I've no idea how to dig into that.

**Comment by jpjp** [comment] 2015-07-03 06:50
I followed the documentation (which isn't good, actually- it's consistent), and it says to set:

        services.sync.tokenServerURI: http://sync.example.com/token/1.0/sync/1.5

Anyway, I am not having this issue any more because I have moved on, so maybe the next person who has this problem can continue. Thanks.

**Comment by rfk** [comment] 2015-07-03 14:57
OK, closing this out

**Closed by rfk** 2015-07-03 14:57 UTC

**Comment by Nlar** [comment] 2015-08-12 04:55
I had the same issue and it was caused by a disconnect between the services.sync.tokenServerURI and the services.sync.clusterURL.  If both services are running off the root there isn't a problem, but if they are not firefox (at least Firefox Developer Edition 38.1.1) will rewrite the services.sync.clusterURL every time the sync activates.  

If a proxy is used the the clusterURL must be accounted for in my experience.  If you are running your sync server off of http://sync.examples.com/ffsync, then you must have something else that serves https://examples.com/storage

Final about:config settings:
>services.sync.clusterURL: http://sync.example.com/storage/1.5/1/
>services.sync.tokenServerURI: http://sync.example.com/token/1.0/sync/1.5/

**Comment by rfk** [comment] 2015-08-14 04:41
FYI, `clusterURL` should not be set manually, part of the sync protocol is that the client discovers its appropriate `clusterURL` at runtime.  If you were getting an invalid value for `clusterURL` it's probably due to some configuration issue on the server.

**Comment by rfk** [comment] 2015-08-14 04:42
The modified subscription endpoint is now available in basket: https://bugzilla.mozilla.org/show_bug.cgi?id=1193364
