### ISSUE TITLE
Signin unblock doesn't work after changing primary email

### ISSUE THREAD

**Issue by turtleloveshoes** [mozilla/fxa-auth-server#2256] opened 2018-01-17 00:16 UTC
HI there, 
I am reporting an issue for a user that is experiencing issues for signing in with 2FA turned on in beta and release (57)

https://support.mozilla.org/en-US/questions/1199655#answer-1065779

I will ask the user to add the steps to get here.

**Comment by budkin** [comment] 2018-01-17 01:47
Okay, so I usually sign in on Linux, but this time I tried to sign in on windows. I use the latest stable version of Firefox

**Comment by philbooth** [comment] 2018-01-18 17:48
Hey @budkin, we did have a service outage around 7am UTC on Wednesday, not sure if this is related to that problem. Can you try again and let us know if it's fixed, if not can you describe more clearly exactly what error you're getting?

**Comment by budkin** [comment] 2018-01-18 19:03
>not sure if this is related to that problem

it probably isn't, because I had this problem earlier

>more clearly exactly what error you're getting
if you follow that link, it's all there. the error message read "Primary account email required for sign-in"

I don't have this problem anymore

**Comment by philbooth** [comment] 2018-01-18 19:08
> I don't have this problem anymore

Great! Closing this.

**Comment by rfk** [comment] 2018-01-18 19:51
I'm going to re-open and assign this to myself, because I want to double-check a theory about how this might have happened...

**Comment by rfk** [comment] 2018-01-19 04:38
I think I managed to reproduce the error @budkin ran in to.

> I don't remember how I enabled 2FA, maybe it was on by default?

If I interpret your comments correctly, I think you were seeing our "signin unblock" screen.  This screen triggers when we see something suspicious about a user's login attempt.  Maybe they have entered too many incorrect password attempts, maybe their IP is on a third-party blocklist, stuff like that.  We send a confirmation code to your email as an additional security measure in these cases.

Based on that, here's my steps to reproduce what I think you were seeing:

* Create a new account
* Add and verify a secondary email address.
* Switch the secondary address to be primary.
* Sign out.
* Attempt to sign back in using the new primary email address, but typo your password.
* Keep trying to log in with an incorrect password, until you trigger the signin unblock screen
* Observe that the screen says that we sent an unblock code to the *old* primary address, rather than the new one.
  * However, we actually sent the to both addresses.
* Try to enter the code from the email to continue with the signin.

Expected result:

* The code is successfully consumed.

Actual result:

* An error telling me that I have to sign in using my primary address, despite the fact that I *was* trying to sign in with my primary address.

It's not clear to me whether the bug is in auth-server or content-server, but it's definitely a bug *somewhere*.  Given that the unblock screen displays the old primary address, I suspect it may be a content-server bug.

/cc @vbudhram

**Comment by rfk** [comment] 2018-01-19 04:40
(I'm also putting this back into "triage" for further discussion, now that we're able to repro)

**Comment by budkin** [comment] 2018-01-19 04:48
yes! those steps are the exact very thing I have gone through, I think

**Comment by vbudhram** [comment] 2018-01-22 19:31
@rfk Nice find! I suspect that this is most likely a content-server bug. Assigning myself so that I can dig in a little more.

**Comment by rfk** [comment] 2018-04-12 02:39
This bug has returned, as reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1453152

**Comment by rfk** [comment] 2018-04-12 02:49
The sequence of requests made by content-server here goes:

* `/account/login` with `{ email: "new_primary", password: "incorrect pw" }`
    * This returns a 400 with `{ errno: 120, email: "old_primary"}`
* Automatic retry of `/account/login` with `{ email: "old_primary", originalLoginEmail: "new_primary", password: "incorrect pw"}`
    * This returns a 400 with `{ errno: 103, email: "old_primary"}`
* Repeat the above until rate-limiting kicks in, returning a 429 with `{verificationMethod: "email-captcha"}`
* `/send_unblock_code` with `{ email: "old_primary" }`
* (I get the code from my email and enter it into the form)
* `/account/login` with `{email: "old_primary", password: "incorrect pw", unblockCode: "code"}`
    * This returns a 400 with `{errno: 142}`, triggering the "primary email required for sign-in" error message.

So I think what's gone wrong here, is that when I enter the unblock code and retry the login, content-server has forgotten the "originalLoginEmail" parameter.  If I manually intercept the request and add the "originalLoginEmail" parameter then it behaves as expected (in this case, accepting the unblock code and returning an "incorrect password" error).

**Comment by rfk** [comment] 2018-04-12 02:55
Since this appears to be a content-server issue, I'm migrating it to https://github.com/mozilla/fxa-content-server/issues/6049

**Closed by rfk** 2018-04-12 02:55 UTC
Labels: waffle:review
