### ISSUE TITLE
Unblock Code Not Always Working

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1562] opened 2016-11-22 05:50 UTC
There have been various reports that the unblock code isn't working. This warrants investigations. Here are the 3 I heard of today:

https://bugzilla.mozilla.org/show_bug.cgi?id=1317731

https://bugzilla.mozilla.org/show_bug.cgi?id=1318649

Also mentioned in the comments of this Facebook post: 
https://www.facebook.com/Firefox/posts/10157770892500022

**Comment by rfk** [comment] 2016-11-22 06:16
/cc @seanmonstar 

There are at least three reasons why a code might be rejected:

* It has expired
* It doesn't exist in the database
* It has already been used

It would be useful to emit a different metrics event for each of these three cases to help figure out what's going on here.

**Comment by seanmonstar** [comment] 2016-11-22 18:50
- There is [`Account.login.unblockCode.expired` logged here](https://github.com/mozilla/fxa-auth-server/blob/v1.74.0/lib/routes/account.js#L483). I tried looking in kibana for this log line and was not having success. Either I was doing it wrong, or no one ever uses an expired code!
- To handle the other 2 instances, we'd need to update the auth server to not delete codes upon use, but to instead mark them as used (and leave them in the DB, perhaps to be cleaned up in a monthly sweep).

An additional data point for prioritizing: The vast majority of users do have functioning unblock codes. The sevice is working most of the time, we see about 80% of sent codes are successfully used. This should still be investigated, just clarifying that this isn't "everything is broken" bug.

**Comment by davismtl** [comment] 2016-11-22 18:58
I agree, metrics show that it is working for most users.

This is what will make it even harder to debug (IMO). It seems intermittent or to only impact some people. 

Ahh UX... when we blocked everyone, no one complained. Give users an option to unblock that doesn't work (sometimes), we get complaints. ;)

**Comment by rfk** [comment] 2016-11-22 19:26
Yeah, I remember someone (alright alright, it was me) saying something like "they're blocked, we can't possible give these users any worse of a time than they're already getting!".  But apparently we can, at least for some of them.

**Comment by shane-tomlinson** [comment] 2016-11-23 10:31
> But apparently we can, at least for some of them.

It's confusing which could be considered worse, but for the majority this is still a better experience so I'm not too worried.

I have another possibility, based on @seanmonstar's comment [in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1318649#c6). We trim entered values to reduce the number of occurrences of copy/paste errors with whitespace on the ends, but do not remove any whitespace from the middle. It's possible some subset of users accidentally enter whitespace in the middle, which would cause an "invalid unblock code"

**Comment by rfk** [comment] 2016-11-23 10:34
If the code has the wrong number of characters, it should fail Hapi validation and produce a general "invalid parameter in request" error rather than the unblock-specific "invalid code" error.  Which may mean that we can test this hypothesis by looking for any increase the rate of such errors.

**Comment by shane-tomlinson** [comment] 2016-11-23 10:51
> If the code has the wrong number of characters, it should fail Hapi validation and produce a general "invalid parameter in request" error rather than the unblock-specific "invalid code" error.

If the user went through the content server front-end, an unblock code with an invalid number of characters won't even have the chance to be sent to the auth server.

**Comment by vbudhram** [comment] 2016-11-23 16:54
Per @shane-tomlinson inquiry, looked into customs server unblocking mechanisms and found something confusing. From the looks of it, it does not not appear to return the correct `retryAfter` if rate limited by an unblock action. 

Ref: https://github.com/mozilla/fxa-customs-server/blob/master/lib/email_record.js#L135 and https://github.com/mozilla/fxa-customs-server/blob/master/lib/server.js#L152

@seanmonstar @rfk Is the current state the expected functionality? I very well could be going down a rabbit hole.

**Comment by rfk** [comment] 2016-11-23 19:48
The rate-limiting of unblock attempts is a little different.  Customs-server returns an additional field "unblock" in its response, to say whether the user is allowed to unblock this block:

  https://github.com/mozilla/fxa-customs-server/blob/master/lib/server.js#L181

This comes from the `canUnblock` method of the email record:

  https://github.com/mozilla/fxa-customs-server/blob/master/lib/server.js#L163

Which does the usual trim-and-count logic that we're all familiar with:

  https://github.com/mozilla/fxa-customs-server/blob/master/lib/email_record.js#L89

The result is that doing too many unblock attempts shouldn't cause you to get rate-limited in and of itself.  It will just revoke your ability to make any further unblock attempts.

**Comment by rfk** [comment] 2016-11-24 05:39
Oh, there was also this report: https://github.com/mozilla/addons/issues/281

**Comment by shane-tomlinson** [comment] 2016-11-24 11:14
Is the ban period of a user extended when they try to unblock themselves and enter an incorrect code? Is it possible for a user who enters an incorrect code to become hard blocked, and the unblock code is ignored?

**Comment by rfk** [comment] 2016-11-27 23:13
Another report: https://www.reddit.com/r/firefox/comments/5f6mn6/invalid_authorization_code_sync_signin/

**Comment by rfk** [comment] 2016-11-27 23:20
A bad interaction between the logic in customs-server and auth-server does seem like a plausible suspect here, but I'm not sure how that could surface as an "invalid authorization code" error.  Even if the unblock code is getting ignored, ISTM this should produce a 412 "attempt limit exceeded" rather than an error message about the code.

(Which of course may be a clue, if we can identify such a code path)

**Comment by rfk** [comment] 2016-11-27 23:28
> Is it possible for a user who enters an incorrect code to become hard blocked

Invalid unblock codes are indeed flagged as failed login attempts, so there could be some feedback loop in play here.

**Comment by rfk** [comment] 2016-11-28 02:30
Here's the flow metrics sequences for some users who had recently a bad time, and wound up with an `invalidUnblockCode` error:

```
 flow_time | flow_id   |                type                
-----------+-----------+------------------------------------
         0 | 6a0ac39   | flow.signin.begin
      1309 | 6a0ac39   | flow.signin.engage
      4832 | 6a0ac39   | flow.signin.submit
     29676 | 6a0ac39   | flow.signin.submit
     37849 | 6a0ac39   | flow.signin.submit
     71822 | 6a0ac39   | flow.signin.submit
     85567 | 6a0ac39   | flow.signin.submit
    103698 | 6a0ac39   | customs.blocked
    103702 | 6a0ac39   | flow.signin.submit
    103929 | 6a0ac39   | account.login.sentUnblockCode
    340555 | 6a0ac39   | flow.signin-unblock.engage
    350387 | 6a0ac39   | flow.signin.submit
    350415 | 6a0ac39   | customs.blocked
    350415 | 6a0ac39   | account.login.blocked
    350429 | 6a0ac39   | account.login.invalidUnblockCode
    375292 | 6a0ac39   | customs.blocked
    375292 | 6a0ac39   | account.login.blocked
    375314 | 6a0ac39   | account.login.confirmedUnblockCode
    375538 | 6a0ac39   | flow.signin.submit
    389319 | 6a0ac39   | customs.blocked
    389473 | 6a0ac39   | flow.signin.submit
    389478 | 6a0ac39   | account.login.sentUnblockCode
    430163 | 6a0ac39   | customs.blocked
    430177 | 6a0ac39   | account.login.confirmedUnblockCode
    430349 | 6a0ac39   | flow.signin.submit
    467777 | 6a0ac39   | customs.blocked
    467927 | 6a0ac39   | account.login.sentUnblockCode
    467928 | 6a0ac39   | flow.signin.submit
    612005 | 6a0ac39   | flow.signin.submit
    612265 | 6a0ac39   | customs.blocked
    612265 | 6a0ac39   | account.login.blocked
    612277 | 6a0ac39   | account.login.invalidUnblockCode
    637940 | 6a0ac39   | flow.signin.submit
    637976 | 6a0ac39   | customs.blocked
    645247 | 6a0ac39   | flow.signin.submit
    645257 | 6a0ac39   | customs.blocked
    659125 | 6a0ac39   | customs.blocked
```

```
 flow_time | flow_id |                type                
-----------+---------+------------------------------------
         0 | 5d69087 | flow.signup.begin
     13090 | 5d69087 | flow.signup.engage
     70241 | 5d69087 | flow.signup.submit
     71888 | 5d69087 | flow.signin.submit
     80351 | 5d69087 | customs.blocked
     80854 | 5d69087 | account.login.sentUnblockCode
     81918 | 5d69087 | flow.signin.engage
     81959 | 5d69087 | flow.signin.submit
    105963 | 5d69087 | flow.signin-unblock.engage
    132770 | 5d69087 | customs.blocked
    132795 | 5d69087 | account.login.confirmedUnblockCode
    133199 | 5d69087 | customs.blocked
    133199 | 5d69087 | account.login.blocked
    133215 | 5d69087 | account.login.invalidUnblockCode
    134703 | 5d69087 | flow.signin.submit
```

```
 flow_time | flow_id |                type                
-----------+---------+------------------------------------
         0 | 628c824 | flow.signin.begin
     31537 | 628c824 | flow.signin.engage
     41514 | 628c824 | flow.signin.submit
     59190 | 628c824 | customs.blocked
     59494 | 628c824 | account.login.sentUnblockCode
     59646 | 628c824 | flow.signin.submit
     82815 | 628c824 | flow.signin-unblock.engage
     86586 | 628c824 | customs.blocked
     86587 | 628c824 | account.login.blocked
     86603 | 628c824 | account.login.confirmedUnblockCode
     86765 | 628c824 | customs.blocked
     87216 | 628c824 | flow.signin.submit
    113536 | 628c824 | customs.blocked
    114173 | 628c824 | flow.signin.submit
    170730 | 628c824 | customs.blocked
    170730 | 628c824 | account.login.blocked
    170749 | 628c824 | account.login.invalidUnblockCode
    171381 | 628c824 | flow.signin.submit
```

Some of these sequences just don't look right, e.g. `confirmedUnblockCode` followed by `customs.blocked`, or a `confirmedUnblockCode` followed by an `invalidUnblockCode` without any additional form submissions in between.  May be some clues in here.

**Comment by rfk** [comment] 2016-11-28 03:20
A related calculation in redash:

  https://sql.telemetry.mozilla.org/queries/1779/source

This shows that number of flows that request an unblock code, the number that then get an "invalidUnblockCode" error, and the number that get that error *without also getting* a "confirmUnblockCode".

The numbers are interesting:

* About 25% of people who send themselves an unblock code, get an "invalidUnblockCode" event. 
* Of that 25%, more than 90% *also* get a "confirmUnblockCode" event.

Is that because they're succeeding at entering the code, or because some bug is causing it to be consumed without actually processing the login attempt?

**Comment by rfk** [comment] 2016-11-28 03:46
Here's another flow that doesn't seem to make sense:

```
         0 | 9271a78 | flow.signin.begin
      1250 | 9271a78 | flow.signin.engage
      3170 | 9271a78 | flow.signin.submit
      3940 | 9271a78 | customs.blocked
      3941 | 9271a78 | account.login.blocked
      4486 | 9271a78 | account.login.sentUnblockCode
     94482 | 9271a78 | flow.signin-unblock.engage
     95748 | 9271a78 | flow.signin.submit
     95749 | 9271a78 | customs.blocked
     95749 | 9271a78 | account.login.blocked
     95767 | 9271a78 | account.login.confirmedUnblockCode
     96000 | 9271a78 | customs.blocked
     96000 | 9271a78 | account.login.blocked
     96013 | 9271a78 | account.login.invalidUnblockCode
    122697 | 9271a78 | flow.signin.submit
    122765 | 9271a78 | customs.blocked
    122765 | 9271a78 | account.login.blocked
    122775 | 9271a78 | account.login.invalidUnblockCode
    134044 | 9271a78 | account.login.sentUnblockCode
    169395 | 9271a78 | flow.signin.submit
    169466 | 9271a78 | customs.blocked
    169466 | 9271a78 | account.login.blocked
    169481 | 9271a78 | account.login.confirmedUnblockCode
    169712 | 9271a78 | customs.blocked
    169712 | 9271a78 | account.login.blocked
    169722 | 9271a78 | account.login.invalidUnblockCode
```

This contains four `flow.signin.submit` events, two "confirmedUnblockCode" events, and three "invalidUnblockCode" events.  Why are there five "*UnblockCode" events for only four submit events?

Could we be accidentally consuming the valid code no a login attempt that fails, then re-trying a second login attempt with the same code?

**Comment by rfk** [comment] 2016-11-28 03:53
Oh snap, I can reproduce this behaviour if I try to login with the incorrect case for my email address.  This screenshot sums it up:

![screen shot 2016-11-28 at 14 48 06](https://cloud.githubusercontent.com/assets/34695/20655743/b9c1f50e-b579-11e6-8a7e-7b1f2161da75.png)

My account there is "ryan@rfk.id.au", but I tried to login as "RyAn@rfk.id.au".  The flow of events went like this:

* Submit login attempt, fails with errno=120 "incorrect email case".
* The content-server automatically retries with the correct email case, fails with 103 "bad password".
* I try again, and get the same sequence of two failed attempts, and because the auth-server thinks I've made *four* login attempts, I get rate-limited.
* The content-server requests an unblock code email, and takes me to the unblock screen, where I enter the code from my email.
* Content-server tries a login attempt using the code, it fails with errno=120 "incorrect email case".
* Content-server automatically retries with the correct email case *and the same unblock code*, and it fails with "127" invalid unblock code.

This may not explain all the incidences that have been reported, but it could certainly explain some of them!

**Comment by rfk** [comment] 2016-11-28 04:16
BTW, a quick poke around in re:dash suggests that > 20% of successful unblock flows, send two or more unblock codes before managing to login successfully.  One way to fix the email-case issue here, would be to allow multiple tries per authorization code, and it would probably help those 20% of blocked users as well.

**Comment by rfk** [comment] 2016-11-28 04:19
Also, Kibana says we have a non-trivial number of errno=120 login attempts per hour.  Any of those that get blocked by customs-server, would be hitting the bug above.

**Comment by rfk** [comment] 2016-12-20 04:44
Train75 has shipped so this is no longer blocked; let's review metrics in a couple of days and see if the rate of invalid codes has decreased.

**Comment by rfk** [comment] 2016-12-21 03:38
Here's a graph we can use to check for a decrease in invalid unblock codes:

  https://sql.telemetry.mozilla.org/queries/1958/source#3478

No effect visible yet, but I think we don't yet have the metrics imported from the train-75 deploy.  Once it gets data for December 20 and beyond we can start to draw some conclusions.

**Comment by philbooth** [comment] 2016-12-21 04:33
> Once it gets data for December 20 and beyond we can start to draw some conclusions.

I know when to take a hint! 😄

I happened to be messing around on that box anyway, so I ran the import manually and it finished just now. If you run your query again, it should have the data you're looking for.

**Comment by rfk** [comment] 2016-12-21 04:40
:-P

Wasn't meant to be a hint, I was mucking around with re-importing the data earlier today but it only had up to December 19.

**Comment by rfk** [comment] 2016-12-21 04:42
And waddyaknow, the count of invalid unblock codes for Dec 20 is at least a third lower than it was on the 19th.  A good start!

**Comment by davismtl** [comment] 2016-12-21 22:43
Normally we should see this move too soon as a result: https://sql.telemetry.mozilla.org/queries/1626#2878

**Comment by rfk** [comment] 2016-12-22 05:03
The reduced rate of invalid unblock codes appears stable.  It's dramatically reduced but still a long way from zero, I wonder if there's anything more we can do to figure out whether this is users legitimately entering incorrect codes, or using expired codes, or something else.

**Comment by vladikoff** [comment] 2017-01-09 21:28
from mtg: closing, reopen if there are still issues with this...

**Closed by vladikoff** 2017-01-09 21:28 UTC
Labels: waffle:active
