### ISSUE TITLE
unit tests fail locally on master

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1326] opened 2016-07-05 09:35 UTC
While testing @vbudhram's [PR to fix signin confirmation email sending](https://github.com/mozilla/fxa-auth-server/pull/1317), I consistently saw 3 failing unit tests. Switching to master, these same 3 tests fail. @philbooth says the same 3 always fail for him too.

```bash
not ok test/remote/account_preverified_token_tests.js ... 1/4
    Command: "/Users/stomlinson/.nvm/versions/node/v4.3.0/bin/node account_preverified_token_tests.js"
    TAP version 13
    not ok 1 Invalid verification code
      ---
        file:   /Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/util.js
        line:   26
        column: 23
        stack:
          - |
            getCaller (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:439:17)
          - |
            assert (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:21:16)
          - |
            Function.fail (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:95:10)
          - |
            Test._testAssert [as fail] (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-test.js:87:16)
          - |
            /Users/stomlinson/development/fxa-auth-server/test/ptaptest.js:51:15
          - |
            tryCatcher (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
          - |
            Promise._settlePromiseFromHandler (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
          - |
            Promise._settlePromiseAt (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
          - |
            Promise._settlePromises (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:697:14)
          - |
            Async._drainQueue (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:123:16)
          - |
            Async._drainQueues (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
          - |
            Immediate.Async.drainQueues [as _onImmediate] (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
          - |
            processImmediate [as _immediateCallback] (timers.js:383:17)
      ...
    ok 2 invalid verification code
    not ok 3 Invalid verification code
      ---
        file:   /Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/util.js
        line:   26
        column: 23
        stack:
          - |
            getCaller (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:439:17)
          - |
            assert (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:21:16)
          - |
            Function.fail (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-assert.js:95:10)
          - |
            Test._testAssert [as fail] (/Users/stomlinson/development/fxa-auth-server/node_modules/tap/lib/tap-test.js:87:16)
          - |
            /Users/stomlinson/development/fxa-auth-server/test/ptaptest.js:51:15
          - |
            tryCatcher (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
          - |
            Promise._settlePromiseFromHandler (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
          - |
            Promise._settlePromiseAt (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
          - |
            Promise._settlePromises (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:697:14)
          - |
            Async._drainQueue (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:123:16)
          - |
            Async._drainQueues (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
          - |
            Immediate.Async.drainQueues [as _onImmediate] (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
          - |
            processImmediate [as _immediateCallback] (timers.js:383:17)
      ...
    not ok 4 test/remote/account_preverified_token_tests.js
      ---
        exit:    1
        stderr:  |
          {"Timestamp":1467711210899000000,"Logger":"fxa-auth-server","Type":"","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"env":"dev","log":"{\"level\":\"info\",\"fmt\":\"heka\"}","memcached":"{\"address\":\"127.0.0.1:11211\",\"idle\":30000,\"lifetime\":1800}","publicUrl":"http://127.0.0.1:9000","domain":"127.0.0.1:9000","secretKeyFile":"/Users/stomlinson/development/fxa-auth-server/config/secret-key.json","publicKeyFile":"/Users/stomlinson/development/fxa-auth-server/config/public-key.json","trustedJKUs":"[\"http://127.0.0.1:9000/.well-known/public-keys\"]","db":"{\"backend\":\"httpdb\"}","httpdb":"{\"url\":\"http://127.0.0.1:8000\"}","listen":"{\"host\":\"127.0.0.1\",\"port\":9000}","customsUrl":"none","contentServer":"{\"url\":\"http://127.0.0.1:3030\"}","smtp":"{\"api\":{\"host\":\"127.0.0.1\",\"port\":9001},\"host\":\"127.0.0.1\",\"port\":9999,\"secure\":false,\"sender\":\"Firefox Accounts <no-reply@lcip.org>\",\"verificationUrl\":\"http://127.0.0.1:3030/v1/verify_email\",\"verifyLoginUrl\":\"http://127.0.0.1:3030/complete_signin\",\"passwordResetUrl\":\"http://127.0.0.1:3030/v1/complete_reset_password\",\"accountUnlockUrl\":\"http://127.0.0.1:3030/v1/complete_unlock_account\",\"initiatePasswordResetUrl\":\"http://127.0.0.1:3030/reset_password\",\"syncUrl\":\"https://www.mozilla.org/firefox/sync/\",\"androidUrl\":\"https://www.mozilla.org/firefox/android/\",\"iosUrl\":\"https://www.mozilla.org/firefox/ios/\",\"signInUrl\":\"http://127.0.0.1:3030/signin\",\"supportUrl\":\"https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account\",\"redirectDomain\":\"firefox.com\",\"initiatePasswordChangeUrl\":\"http://127.0.0.1:3030/settings/change_password\"}","maxEventLoopDelay":0,"scrypt":"{\"maxPending\":0}","i18n":"{\"defaultLanguage\":\"en\",\"supportedLanguages\":[\"ar\",\"az\",\"bg\",\"cs\",\"cy\",\"da\",\"de\",\"dsb\",\"en\",\"en-GB\",\"es\",\"es-AR\",\"es-CL\",\"et\",\"fa\",\"ff\",\"fi\",\"fr\",\"fy\",\"he\",\"hi-IN\",\"hsb\",\"hu\",\"it\",\"ja\",\"kk\",\"ko\",\"lt\",\"nl\",\"pa\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"rm\",\"ru\",\"sk\",\"sl\",\"sq\",\"sr\",\"sr-LATN\",\"sv\",\"sv-SE\",\"tr\",\"uk\",\"zh-CN\",\"zh-TW\"]}","tokenLifetimes":"{\"accountResetToken\":900000,\"passwordForgotToken\":3600000,\"passwordChangeToken\":900000}","verifierVersion":1,"snsTopicArn":"disabled","bounces":"{\"region\":\"\",\"bounceQueueUrl\":\"\",\"complaintQueueUrl\":\"\"}","verificationReminders":"{\"rate\":0}","useHttps":false,"keyPath":"/Users/stomlinson/development/fxa-auth-server/key.pem","certPath":"/Users/stomlinson/development/fxa-auth-server/cert.pem","lockoutEnabled":true,"newLoginNotificationEnabled":true,"deviceUpdatesEnabled":true,"oauth":"{\"url\":\"http://localhost:9010\",\"keepAlive\":false,\"extra\":{\"email\":false}}","openIdProviders":"[]","statsd":"{\"enabled\":true,\"host\":\"localhost\",\"port\":8125,\"sample_rate\":0.1}","metrics":"{\"flow_id_key\":\"YOU MUST CHANGE ME\",\"flow_id_expiry\":1800000}","corsOrigin":"[\"http://foo\",\"http://bar\"]","clientAddressDepth":3,"signinConfirmation":"{\"enabled\":false,\"sample_rate\":1,\"supportedClients\":[\"iframe\",\"fx_firstrun_v1\",\"fx_firstrun_v2\",\"fx_desktop_v1\",\"fx_desktop_v2\",\"fx_desktop_v3\"],\"forceEmailRegex\":[\".+@mozilla.com$\"]}","isProduction":false,"openIdVerifyUrl":"http://127.0.0.1:9000/v1/account/openid/login"}}
          {"Timestamp":1467711212575000000,"Logger":"fxa-auth-server","Type":"server.start.1","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"server.start.1","msg":"running on http://127.0.0.1:9000"}}
          {"Timestamp":1467711212627000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1467711212614:Shanes-Retina-MBP.local:18454:iq99czin:10000","path":"/__heartbeat__","remoteAddressChain":"[\"127.0.0.1\"]","t":13,"uid":"00"}}
          {"Timestamp":1467711212665000000,"Logger":"fxa-auth-server","Type":"metrics.context.validate","Severity":4,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metrics.context.validate","valid":false,"reason":"missing flowId"}}
          {"Timestamp":1467711212677000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1467711212676:Shanes-Retina-MBP.local:18454:iq99czin:10002","path":"/.well-known/public-keys","agent":"FetchStream","remoteAddressChain":"[\"127.0.0.1\"]","t":1,"uid":"00"}}
          {"Timestamp":1467711212686000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":400,"errno":105,"rid":"1467711212658:Shanes-Retina-MBP.local:18454:iq99czin:10001","path":"/v1/account/create","remoteAddressChain":"[\"127.0.0.1\"]","t":28,"uid":"00","keys":"true","email":"4cbf7aeef4481cd6e8a0@restmail.net"}}
          undefined
          {"Timestamp":1467711212705000000,"Logger":"fxa-auth-server","Type":"metrics.context.validate","Severity":4,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metrics.context.validate","valid":false,"reason":"missing flowId"}}
          {"Timestamp":1467711212709000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1467711212708:Shanes-Retina-MBP.local:18454:iq99czin:10004","path":"/.well-known/public-keys","agent":"FetchStream","remoteAddressChain":"[\"127.0.0.1\"]","t":1,"uid":"00"}}
          {"Timestamp":1467711212711000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":400,"errno":105,"rid":"1467711212704:Shanes-Retina-MBP.local:18454:iq99czin:10003","path":"/v1/account/create","remoteAddressChain":"[\"127.0.0.1\"]","t":7,"uid":"00","email":"4363b5fd1aed6ab00f92@restmail.net"}}
          {"Timestamp":1467711212730000000,"Logger":"fxa-auth-server","Type":"metrics.context.validate","Severity":4,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metrics.context.validate","valid":false,"reason":"missing flowId"}}
          {"Timestamp":1467711212864000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"account.create.emptyLocale","email":"3b509f4ba1bca38bd263@restmail.net"}}
          {"Timestamp":1467711212870000000,"Logger":"fxa-auth-server","Type":"activityEvent","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"event":"account.created","time":1467711212870,"flow_time":null,"context":"fx_desktop_v3","uid":"48c5311bb020478983d9e5bb11c40025"}}
          {"Timestamp":1467711213885000000,"Logger":"fxa-auth-server","Type":"metricsContext.stash","Severity":2,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metricsContext.stash","err":"Error: connect ECONNREFUSED 127.0.0.1:11211"}}
          {"Timestamp":1467711213885000000,"Logger":"fxa-auth-server","Type":"metricsContext.stash","Severity":2,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metricsContext.stash","err":"Error: connect ECONNREFUSED 127.0.0.1:11211"}}
          {"Timestamp":1467711213888000000,"Logger":"fxa-auth-server","Type":"metricsContext.stash","Severity":2,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metricsContext.stash","err":"Error: Server at 127.0.0.1:11211 not available"}}
          {"Timestamp":1467711213906000000,"Logger":"fxa-auth-server","Type":"mailer.send","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"email":"3b509f4ba1bca38bd263@restmail.net","op":"mailer.send","template":"verifyEmail"}}
          {"Timestamp":1467711213912000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1467711212729:Shanes-Retina-MBP.local:18454:iq99czin:10005","path":"/v1/account/create","remoteAddressChain":"[\"127.0.0.1\"]","t":1183,"uid":"00","email":"3b509f4ba1bca38bd263@restmail.net"}}
          (node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
          {"Timestamp":1467711214005000000,"Logger":"fxa-auth-server","Type":"metrics.context.validate","Severity":4,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"metrics.context.validate","valid":false,"reason":"missing flowId"}}
          {"Timestamp":1467711214011000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1467711214011:Shanes-Retina-MBP.local:18454:iq99czin:10007","path":"/.well-known/public-keys","agent":"FetchStream","remoteAddressChain":"[\"127.0.0.1\"]","t":0,"uid":"00"}}
          {"Timestamp":1467711214013000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":400,"errno":105,"rid":"1467711214004:Shanes-Retina-MBP.local:18454:iq99czin:10006","path":"/v1/account/create","remoteAddressChain":"[\"127.0.0.1\"]","accountRecreated":true,"t":9,"uid":"00","email":"3b509f4ba1bca38bd263@restmail.net"}}
          undefined
          {"Timestamp":1467711214016000000,"Logger":"fxa-auth-server","Type":"shutdown","Severity":6,"Pid":18454,"EnvVersion":"2.0","Fields":{"op":"shutdown"}}
        command: "/Users/stomlinson/.nvm/versions/node/v4.3.0/bin/node account_preverified_token_tests.js"
      ...

    1..4
    # tests 4
    # pass  1
    # fail  3

ok test/remote/account_profile_tests.js ............... 22/22
```

**Comment by philbooth** [comment] 2016-07-05 10:03
> @philbooth says the same 3 always fail for him too.

Yep, just to clarify: These 3 tests have never worked locally for me, I rely on CI or a VM to tell me whether they pass. Assumed it was because of something stupid I'd done to my machine.

**Comment by vladikoff** [comment] 2016-07-05 13:21
> These 3 tests have never worked locally for me, I rely on CI or a VM to tell me whether they pass. Assumed it was because of something stupid I'd done to my machine.

Same here. 
<img src=http://v14d.com/i/577bb434261ac.jpg width=75 />

**Comment by philbooth** [comment] 2016-07-05 14:57
At least in my case, I appear to be getting an `unknown kid` which comes from `fxa-jwtool`:

https://github.com/mozilla/fxa-jwtool/blob/master/index.js#L193

Still trying to figure out why.

**Comment by rfk** [comment] 2016-07-06 06:57
FWIW, they pass locally for me, but I've no idea what magic I worked in order to make that so...

**Comment by philbooth** [comment] 2016-07-06 09:45
Returning this to the backlog. I tried digging into it a bit but struggled to follow what's going on in `fxa-jwtool` and didn't want to waste too much time on it.

**Comment by vladikoff** [comment] 2016-07-11 17:22
My current status with this:

` node_modules/.bin/tap test/local/account_routes.js` - passes when fxa-auth-server runs locally via `npm start`. fails otherwise. @vbudhram can you check this case again (with a stopped auth-server)?

`node_modules/.bin/tap  test/local/base_path_tests.js` - passes when i stop the local fxa-auth-server. @vbudhram reports that these tests pass for him even if the auth-server is running locally.

I run things via `node_modules/.bin/tap  test/local/base_path_tests.js` to isolate test
Should `npm test` require you to have fxa-auth-server running locally or no?

**Comment by rfk** [comment] 2016-07-12 04:28
> node_modules/.bin/tap test/local/account_routes.js

This passes for me, with or without the auth-server running locally via `npm start`.

> node_modules/.bin/tap test/local/base_path_tests.js

Same as @vladikoff here - passes when a local auth-server is not running, fails if one is running.

> Should npm test require you to have fxa-auth-server running locally or no?

No, definitely should not.

**Comment by vladikoff** [comment] 2016-07-12 16:30
Found a note at https://github.com/mozilla/fxa-auth-server#testing

> Note: stop the auth-server before running tests. Otherwise, they will fail with obscure errors.

**Comment by vbudhram** [comment] 2016-07-12 18:07
> Should npm test require you to have fxa-auth-server running locally or no?

No, I don't believe it should. The tests are independent and start/stop the servers they need. Something I did notice that might be a factor and related to [this](https://github.com/mozilla/fxa-auth-server/issues/1311), is that `remote` tests might not kill all the processes it spawns, this will cause subsequent remote tests to fail. Killing all the processes and re-running tests will fix the problem. @shane-tomlinson @philbooth can you try running tests with no related FxA node processes running?

**Comment by philbooth** [comment] 2016-07-12 18:26
> can you try running tests with no related FxA node processes running?

I only run them without other stuff running fwiw. I don't believe this issue is related to that.

**Comment by vladikoff** [comment] 2016-07-12 20:17
I did a fresh checkout of master and got all things to pass by stopping all other servers and just running `npm test`. @philbooth could you try the same to confirm?

Result:
```
> fxa-auth-server@1.64.0 test /Users/vladikoff/tmp/fxa-auth-server
> NODE_ENV=dev CORS_ORIGIN=http://foo,http://bar scripts/test-local.sh

OK: List of supported languages match content server config
ok test/local/account_reset_token_tests.js ............ 10/10
ok test/local/account_routes.js ..................... 215/215
ok test/local/base_path_tests.js ...................... 13/13
ok test/local/bounce_tests.js ......................... 60/60
ok test/local/butil_tests.js .......................... 30/30
ok test/local/concurrent_tests.js ....................... 2/2
ok test/local/customs.js .............................. 62/62
ok test/local/db_tests.js ........................... 117/117
ok test/local/email_validity_tests.js ................. 17/17
ok test/local/error_tests.js .......................... 27/27
ok test/local/forgot_password_token_tests.js .......... 16/16
ok test/local/hkdf_tests.js ............................. 6/6
ok test/local/key_fetch_token_tests.js ................ 19/19
ok test/local/log_tests.js .......................... 123/123
ok test/local/mailer_locales_tests.js ................. 63/63
ok test/local/metrics_context_tests.js .............. 179/179
ok test/local/password_check_test.js .................. 17/17
ok test/local/password_routes.js ........................ 9/9
ok test/local/password_tests.js ....................... 11/11
ok test/local/pbkdf2_tests.js ........................... 4/4
ok test/local/pool_tests.js ........................... 59/59
ok test/local/push_db_tests.js ........................ 13/13
ok test/local/push_tests.js ......................... 449/449
ok test/local/scrypt_tests.js ........................... 6/6
ok test/local/session_token_tests.js .................. 68/68
ok test/local/sign_key_tests.js ......................... 4/4
ok test/local/sign_routes.js ............................ 6/6
ok test/local/statsd_tests.js ......................... 29/29
ok test/local/token_expiry_tests.js ..................... 1/1
ok test/local/user_agent_tests.js ..................... 29/29
ok test/local/verification_reminder_db_tests.js ......... 2/2
ok test/local/verification_reminder_tests.js ............ 7/7
ok test/local/verifier_upgrade_tests.js ................. 3/3
ok test/remote/account_create_tests.js ................ 44/44
ok test/remote/account_destroy_tests.js ................. 7/7
ok test/remote/account_locale_tests.js .................. 5/5
ok test/remote/account_login_tests.js ................. 17/17
ok test/remote/account_preverified_token_tests.js ....... 7/7
ok test/remote/account_profile_tests.js ............... 22/22
ok test/remote/account_reset_tests.js ................. 23/23
ok test/remote/account_signin_verification_enable_tests.js  13/13
ok test/remote/account_signin_verification_tests.js ... 97/97
ok test/remote/account_status_tests.js ................ 13/13
ok test/remote/account_unlock_tests.js ................ 15/15
ok test/remote/certificate_sign_tests.js .............. 23/23
ok test/remote/device_tests.js ........................ 66/66
ok test/remote/flow_tests.js .......................... 14/14
ok test/remote/misc_tests.js .......................... 30/30
ok test/remote/password_change_tests.js ............... 42/42
ok test/remote/password_forgot_tests.js ............... 29/29
ok test/remote/recovery_email_resend_code_tests.js ...... 9/9
ok test/remote/recovery_email_verify_tests.js ........... 8/8
ok test/remote/session_destroy_tests.js ................. 5/5
total ............................................. 2165/2165

ok
code coverage: 93.4%
generating coverage.html...
- complete in 7.2s
Running "eslint:files" (eslint) task


Running "copyright:app" (copyright) task

Done, without errors.
➜  fxa-auth-server git:(master) 
```

**Comment by philbooth** [comment] 2016-07-12 20:20
> @philbooth could you try the same to confirm?

I can confirm that it makes no difference, `test/remote/account_preverified_token_tests.js` still fails. Fwiw, this is how I was running the tests anyway. I never run them with a server running.

**Comment by vladikoff** [comment] 2016-07-12 20:25
@philbooth ah, okay. sorry i forgot to specify, I was on node 4.2.3 with a fresh `git clone`.

**Comment by philbooth** [comment] 2016-07-12 20:34
> @philbooth ah, okay. sorry i forgot to specify, I was on node 4.2.3 with a fresh `git clone`.

Reverted node to 4.2.3, fresh clone of the repo, `npm i` then `npm test`, still fails.

**Comment by philbooth** [comment] 2016-07-12 20:35
> ...still fails.

Correct, I'm getting a different failure now actually, it was `test/local/verification_reminder_tests.js` this time. Hmmm....

**Comment by vbudhram** [comment] 2016-07-12 20:48
> test/local/verification_reminder_tests.js

Possibly drop and recreate auth database?

**Comment by philbooth** [comment] 2016-07-12 20:52
> Possibly drop and recreate auth database?

This was against the memory db. But anyway, I think it was the same failure we see intermittently in CI. The second test run passed.

But if I go back to my original clone, `rm -rf node_modules`, `git pull`, `npm i`, `npm t`, I get the original failures again. What's going on there?

**Comment by rfk** [comment] 2016-07-12 22:35
@philbooth so what was different about the original clone, different version of node?

**Comment by philbooth** [comment] 2016-07-13 08:40
> @philbooth so what was different about the original clone, different version of node?

Well, it was *before*, but not now. And I've just done it again to verify that I wasn't hallucinating last night, the failures are repeatable.

I'm not sure the node version is significant here, if I go back to node 4.4.7 and test the fresh clone again, both without clobbering `node_modules` and then with, it still passed all the tests.

Maybe it is dependency-related? Does npm cache any project-specific stuff somewhere else, away from the project's `node_modules`?

Investigating that question a bit more, I did try this experiment to see if anything was cached locally against the full path on my file system:

* `mv fxa-auth-server fxa-auth-server.failing`
* `mv fxa-auth-server.passing fxa-auth-server.failing`
* `cd fxa-auth-server.failing`
* `rm -rf node_modules`
* `npm i`
* `npm t` (tests still fail)
* `cd ../fxa-auth-server`
* `rm -rf node_modules`
* `npm i`
* `npm t` (tests still pass)

So the tainted repo is tainted regardless of path and the untainted one remains untainted.

Anyway, at least I know how to stop it happening if it ever starts again. Would be nice to understand the root cause, though.

**Comment by shane-tomlinson** [comment] 2016-07-22 15:53
I just did the fresh clone process and the tests pass for me now. When I ran the tests in the new clone, the first thing that happens is:

> Generating keypair
Secret Key saved: /Users/stomlinson/development/fxa-auth-server/config/secret-key.json
Public Key saved: /Users/stomlinson/development/fxa-auth-server/config/public-key.json

`unknown kid` is `unknown key id`, perhaps the old secret/public keys are no longer valid or of a bad format?

If I go to the old repo and delete the two keys, re-run the tests, hooray, everything works!

**Comment by philbooth** [comment] 2016-07-22 17:08
> perhaps the old secret/public keys are no longer valid or of a bad format?
>
> If I go to the old repo and delete the two keys, re-run the tests, hooray, everything works!

Excellent sleuthing @shane-tomlinson! Closing this in that case.

**Closed by philbooth** 2016-07-22 17:08 UTC
Labels: waffle:backlog
