### ISSUE TITLE
Investigate scrypt malloc error

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2972] opened 2019-03-18 06:54 UTC
With node 10, we migrated to node's built-in implementation of scrypt, which requires you to specify the upper limit for memory available to the scrypt operation. ~~We store ours in a `const` called `DEFAULT_MAXMEM` in `lib/crypto/scrypt.js`.~~

This error from Sentry seems to indicate that the limit we calculate for that is not sufficient on occasion:

https://sentry.prod.mozaws.net/operations/auth-prod/issues/5373526/?environment=prod

**Comment by philbooth** [comment] 2019-03-18 06:58
Correction, we calculate ours according to the values for `N` and `r`, [here](https://github.com/mozilla/fxa-auth-server/blob/a482770a718025dad726f11b2053b969a284e114/lib/crypto/scrypt.js#L53-L58):

```js
let maxmem = DEFAULT_MAXMEM
if (N > DEFAULT_N || r > DEFAULT_R) {
  // Conservatively prevent `memory limit exceeded` errors. See the docs for more info:
  // https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback
  maxmem = MAXMEM_MULTIPLIER * (N || DEFAULT_N) * (r || DEFAULT_R)
}
```

**Comment by philbooth** [comment] 2019-03-18 07:20
Actually, the linked error seems to imply that `malloc` failed, not that we hit our own limit. So maybe the limit calculation here is okay and the instance ran out of physcial resources instead.

**Comment by jrgm** [comment] 2019-03-19 21:22
Closing. Root cause was likely a severe memory leak in systemd-journald now fixed by reverting to previous AMI images. - https://github.com/mozilla-services/cloudops-deployment/pull/3023

**Closed by jrgm** 2019-03-19 21:22 UTC
Labels: train-134
