### ISSUE TITLE
train-104: /account/create times increased by 66% with this release

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2269] opened 2018-01-30 05:29 UTC
train-104: /account/create times increased by 66% with this release

NOTE: /account/login times did not increase with this release

A manual create confirms the slowdown, but the ux isn't too bad (and `create`/`login` are intentional slow already). 

redis changes in this release did reflect in decreases in BytesUsedForCache (yah!) and general network I/O, but otherwise look uncorrelated. RDS stats look nominal too (although there was a dip in traffic due to a dip in oauth from kinto-we just prior to release). Re-enabled pruning appears to not be blocking concurrent queries so far. 

So not really sure what's up. Smarter folks should have a look /cc @mozilla/fxa-devs

**Comment by philbooth** [comment] 2018-01-30 08:07
This is not at all helpful but I just wanted to record that, having been through all of the auth server and db changes in train 104 one-by-one, I have no idea what is causing this. 😕

**Comment by jrgm** [comment] 2018-01-31 06:34
I tried to reproduce in stage, but I can't. (Well, I can get a small delta in 104 if I tune the loadtest to just do creates, but not really enough to call significant).

Also, something's up with our NR account and I'll have to check on that tomorrow.

**Comment by philbooth** [comment] 2018-01-31 15:04
Fwiw, I tried to reproduce this locally using the MySQL backend and [this script](https://gist.github.com/philbooth/17279a8bebab7f3f40c89d94b0cc6f62). I made sure to migrate the db and blow away `node_modules` between runs to make sure I was testing against the correct version of everything, but didn't see an appreciable difference over a thousand iterations:

```
~/c/fxa-auth-server ((v1.103.0)) $ node scripts/perf-create-account
ITERATIONS: 1001
MEDIAN: 180,087,418 nanoseconds
MEAN: 180,489,654 nanoseconds
```

```
~/c/fxa-auth-server ((v1.104.1)) $ node scripts/perf-create-account
ITERATIONS: 1001
MEDIAN: 188,318,234 nanoseconds
MEAN: 189,140,867 nanoseconds
```

**Comment by philbooth** [comment] 2018-01-31 15:18
Earlier on, @rfk pointed out the coincidence between this slowdown and the significant increase in `utm_source` params set per request. Could something related to how we process those slow down the overall request time?

Nothing leaps out at me from eyeballing the code, but I'm going to modify my test script to see if I can reproduce.

**Comment by vladikoff** [comment] 2018-01-31 15:26
>  I can get a small delta in 104

Seems like the same thing that I saw in my testing, not 66%

**Comment by philbooth** [comment] 2018-01-31 15:53
I may have reproduced this locally now by following up on @rfk's hunch. Adding metrics context to the payload in the test script returned these numbers:

```
~/c/fxa-auth-server ((v1.104.1)) $ node scripts/perf-create-account
ITERATIONS: 1001
MEDIAN: 190,837,565 nanoseconds
MEAN: 522,754,538 nanoseconds
```

So the median hasn't changed but the mean is way off. Digging in some more now to see how many outliers there are and if I can identify the offending code...

**Comment by philbooth** [comment] 2018-01-31 19:39
So there are two clear bands of timings, the majority which are around the normal figure and then a significant number of outliers above the 70th percentile that are much slower:

```
~/c/fxa-auth-server ((v1.104.1)) $ node scripts/perf-create-account
ITERATIONS: 1001
50TH PERCENTILE: 201,596,520 nanoseconds
60TH PERCENTILE: 206,391,773 nanoseconds
70TH PERCENTILE: 1,193,262,732 nanoseconds
80TH PERCENTILE: 1,200,764,542 nanoseconds
90TH PERCENTILE: 1,206,590,042 nanoseconds
95TH PERCENTILE: 1,210,751,196 nanoseconds
99TH PERCENTILE: 1,220,481,251 nanoseconds
100TH PERCENTILE: 1,370,248,307 nanoseconds
MEAN: 533,180,121 nanoseconds
```

I've repeated this over multiple runs and the proportions are always the same, round about the 70th percentile is when the slowdown shows up. Ultimately I found that just an empty object `metricsContext: {}` is sufficient to trigger this behaviour.

Am diving in to the code now...

**Comment by vladikoff** [comment] 2018-01-31 19:50
@philbooth could you gist the script you are using, might be useful for this again or in the future?

**Comment by philbooth** [comment] 2018-01-31 19:55
> could you gist the script you are using, might be useful for this again or in the future?

I refer the right honourable gentleman to https://github.com/mozilla/fxa-auth-server/issues/2269#issuecomment-361959383.

**Comment by vladikoff** [comment] 2018-01-31 19:57
@philbooth Thanks! Sorry I missed the link!

**Comment by rfk** [comment] 2018-01-31 23:15
If these are hitting memcached as part of dealing with the metrics context, it could be some sort of weird perf cliff in memcache e.g. triggering a chance in allocation or eviction behaviour.

**Comment by rfk** [comment] 2018-01-31 23:22
Or, possibly even just waiting for free connections to memcache.

**Comment by philbooth** [comment] 2018-01-31 23:34
> Or, possibly even just waiting for free connections to memcache.

Fwiw, that shouldn't be the case in my tests because my script runs serially, one request at a time. Although that seems like a mistake now I think about it, it's not exactly prod-like conditions is it. I'll add some concurrency in the morning!

**Comment by jrgm** [comment] 2018-02-01 00:10
No prod memcache perf metrics change observed between this train, and previous. No evictions, excessive connections or change in memory size observed.

**Comment by philbooth** [comment] 2018-02-01 10:42
Apologies all, I don't think my comments from yesterday are related to the slowdown in prod after all.

First thing this morning, I added concurrency to the test script and the effect disappeared. I tried with ten-at-a-time, three-at-a-time and two-at-a-time parallelism but always got results like:

```
~/c/fxa-auth-server ((v1.104.1)) $ node scripts/perf-create-account
ITERATIONS: 1001
50TH PERCENTILE: 195,859,872 nanoseconds
60TH PERCENTILE: 197,282,985 nanoseconds
70TH PERCENTILE: 199,578,882 nanoseconds
80TH PERCENTILE: 203,647,777 nanoseconds
90TH PERCENTILE: 207,887,389 nanoseconds
95TH PERCENTILE: 211,102,131 nanoseconds
99TH PERCENTILE: 218,171,962 nanoseconds
100TH PERCENTILE: 284,462,199 nanoseconds
MEAN: 197,466,029 nanoseconds
```

Then I reverted to the non-concurrent version of the script and discovered I can no longer reproduce the behaviour at all. It happened every single time last night so I'm not sure what's different. Maybe it was some kind of memcached idling or swapping out artifact? Whatever it was, it's gone now. 😕

**Comment by philbooth** [comment] 2018-02-01 12:14
> Apologies all, I don't think my comments from yesterday are related to the slowdown in prod after all.

No, wait! I'm an idiot!

I'd a left a change that turned off memcached via config in my working directory last night and forgot about it. Turning that back on, I can reliably reproduce the slowness again and it turns out concurrency does exacerbate the issue. With two-at-a-time parallelism not so much, but with ten-at-a-time I got these numbers:

```
~/c/fxa-auth-server ((v1.104.1)) $ node scripts/perf-create-account
ITERATIONS: 1001
50TH PERCENTILE: 1,496,358,475 nanoseconds
60TH PERCENTILE: 1,601,387,935 nanoseconds
70TH PERCENTILE: 1,629,006,644 nanoseconds
80TH PERCENTILE: 1,698,783,599 nanoseconds
90TH PERCENTILE: 1,795,717,879 nanoseconds
95TH PERCENTILE: 1,817,773,690 nanoseconds
99TH PERCENTILE: 1,866,293,779 nanoseconds
100TH PERCENTILE: 1,928,392,657 nanoseconds
MEAN: 1,339,207,761 nanoseconds
```

So, the upshot is I'm still looking into this after all.

**Comment by philbooth** [comment] 2018-02-01 17:43
> No, wait! I'm an idiot!

In fact I'm a double idiot. For an embarrassing length of time, I did not realise that the memcached service on my machine was stopped. With it started, I see no slowness when running the test script, with or without concurrency.

So whatever's going on in prod, I have no evidence to suggest it's anything to do with either memcached or `metricsContext`.

**Comment by philbooth** [comment] 2018-04-10 09:01
I never got to the bottom of this and it seems like we're living with the slowdown. So, not ideal I realise, but on the basis that nobody's working on it any more, I'm closing this. Feel free to re-open if that's wrong.

**Closed by philbooth** 2018-04-10 09:01 UTC
Labels: waffle:backlog
