### ISSUE TITLE
3 test/local/db_tests failing when using real mysql database

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1028] opened 2015-08-26 18:32 UTC
STR
1. With no other node processes running, clone, npm install and npm start fxa-auth-db-mysql
2. clone, npm install fxa-auth-server
3. run npm test
4. tests fail

(Probably issues with truthiness and mysql for one or two; I'll not that ascii 'A' has hex value '41', so...)

```
not ok test/local/db_tests.js ......................... 62/66
    ok ...
    not ok 17 should be equal
      ---
        file:   /Users/jrgm/tmp33/fxa-auth-server/test/local/db_tests.js
        line:   115
        column: 11
        found:  A
        wanted: 41
        diff:   |
          FOUND:  A
          WANTED: 41
                  ^ (at position = 0)
      ...
    ok ...
    not ok 20 should be equal
      ---
        file:   /Users/jrgm/tmp33/fxa-auth-server/test/local/db_tests.js
        line:   118
        column: 11
        found:  ~
        wanted: ~
        type:   
          found:  undefined
          wanted: undefined
      ...
    ok ...
    not ok 29 should be equal
      ---
        file:   /Users/jrgm/tmp33/fxa-auth-server/test/local/db_tests.js
        line:   136
        column: 11
        found:  ~
        wanted: ~
        type:   
          found:  undefined
          wanted: undefined
      ...
    ok ...
```

**Comment by rfk** [comment] 2015-08-27 04:56
Side note, we should add a real-live-mysql test in travis to help detect this in future.

**Comment by philbooth** [comment] 2015-08-27 09:20
Oh, mea culpa.

The root cause is in `butil.unbuffer` when called from `DB.createSessionToken`, I didn't add an `ignore` option there like I did for `butil.bufferize`. So it sees the string `'41'`, recognises it as hex and we end up with `'A'` which is obviously 0x41 in ASCII.

Adding `waffle:now`.

**Comment by philbooth** [comment] 2015-08-27 13:40
The three linked PRs should sort these issues out. https://github.com/mozilla/fxa-auth-db-mysql/issues/90 and https://github.com/mozilla/fxa-auth-server/issues/1030 are a pair.

Sorry for breaking stuff.

**Comment by rfk** [comment] 2015-08-30 22:56
It looks like the linked PRs are all merged, @philbooth can this be safely closed out now?

**Closed** 2015-08-31 08:55 UTC
Labels: waffle:review
