### ISSUE TITLE
Should we allow multiple login attempts per unblock code?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1575] opened 2016-11-28 19:47 UTC
According to this graph:

  https://sql.telemetry.mozilla.org/queries/1780/source#3198

Of the people that successfully log in using an unblock token, more than 20% of them had to request multiple tokens, which means going through the email loop multiple times.  My guess is they're entering the wrong password on their first unblock attempt.  We could consider allowing multiple tries per code in order to give them a better experience.

In absolute numbers, the multiple-unblock-code users are about a half a percent of all successful logins.

**Comment by vladikoff** [comment] 2016-11-28 19:48
> Should we allow multiple login attempts per unblock code?

Yes, it should "*reset*" their customs server block IMHO

**Comment by shane-tomlinson** [comment] 2016-11-30 11:51
> Yes, it should "reset" their customs server block IMHO

Either this, or allow the user to use an unblock code some low N number of times with an invalid password.

**Comment by rfk** [comment] 2016-11-30 19:56
I think the later will be simpler given the way code is structured in both auth-server and customs-server.

**Comment by vladikoff** [comment] 2016-12-01 17:45
Hashtag Hawaii

**Comment by vladikoff** [comment] 2016-12-28 17:57
@rfk @shane-tomlinson how do we proceed with this?

**Comment by seanmonstar** [comment] 2016-12-28 18:23
If we wanted to do the later ("allow the user to use an unblock code some low N number of times with an invalid password"), we could unwrap the current  `consumeUnblockCode`, into some combination of `checkUnblockCode` and `deleteUnblockCode`. To keep track of N checks, we could add a column `checks_remaining` or similar, and decrement that with each `checkUnblockCode`.

**Comment by rfk** [comment] 2017-01-03 05:29
Trying to decide whether to proceed with this, I made a more detailed graph.  Here we can see an aggregate view of: out of all successful logins that used an unblock code, what percentage sent more than X codes?

  https://sql.telemetry.mozilla.org/queries/2020/source#3636

As noted above, about 20% of of them send two or more codes.  Around 6% send three or more, and it drops off sharply from there.

Looking at the same data, but for *all* login attempts rather than just the successful ones, we see something different:

  https://sql.telemetry.mozilla.org/queries/2020/source#3635

That's 40% of blocked login attempts that send themselves two or more codes, 13% that send 3 or more, and a similarly steep dropoff after 3.

To me, the difference between the two graphs (20% of succesfull logins, 40% of attempted logins) suggests users who are getting frustrated with doing multiple email loops, and abandoning the login process.  Perhaps they've legitimately forgotten their password, but the frustration of doing several authorization loops means they don't bother trying to reset it.

@seanmonstar's proposal for a backend change to allow multiple attempts seems reasonable, but I'm curious about the potential costs on the front-end.  @shane-tomlinson, what's your sense of the difficulty of having content-server use the same unblock code for multiple login attempts?

**Comment by shane-tomlinson** [comment] 2017-01-03 13:52
> @shane-tomlinson, what's your sense of the difficulty of having content-server use the same unblock code for multiple login attempts?

The content-server work should be straight forward. We can pass the unblock code from /signin_unblock to /signin and continue from there. Every subsequent attempt to sign-in will pass the same unblock code. If the number of unblock code re-uses has crossed the threshold and the auth-server returns `verificationReason: 'login', verificationMethod: 'email-captcha', we'll re-send the user to the captcha form.

**Comment by vladikoff** [comment] 2017-01-09 21:31
@davismtl to check the metrics for this...

**Comment by davismtl** [comment] 2017-01-17 22:55
@rfk would users get an invalid code message if they had a bad password or email?
https://sql.telemetry.mozilla.org/queries/1958#3631

From what I can tell, based on these two charts, approx 50% of users that send themselves 2 or more confirmation code succeed at logging in:
https://sql.telemetry.mozilla.org/queries/2020/source#3636
https://sql.telemetry.mozilla.org/queries/2020/source#3635

These charts aside, since this doesn't impact a lot of people, I wouldn't make it very high priority unless it was a trivial change. If it is a trivial change then a code should be good for 2 attempts within 30 or 60 seconds of previous attempts (similarly to regular 2FA codes that reset on a time basis)

**Comment by shane-tomlinson** [comment] 2017-01-18 14:06
> @rfk would users get an invalid code message if they had a bad password or email?
https://sql.telemetry.mozilla.org/queries/1958#3631

Invalid code is only sent if the code itself is invalid, bad emails and passwords log different errors (incorrect password and non-existent account respectively).

If the user enters a valid code but an invalid password, the code will be checked and deleted from the database. The password will then be checked, it will be seen to be invalid, and the user will be shown the "invalid password" screen. They'll need to update their password, the backend will *then* tell them "enter the code from your email." If the new email has not yet arrived and the user copies the old code, or the user just thinks they can use the previous code, then they'll see "invalid code".

Reading the referenced graphs made me curious. None of the graphs tell how many or what percentage of people are giving up at any point in the flow. None of the graphs tell after how many unblock codes people give up. [1] displays stats only for users __that successfully unblock__. It lacks info about people who never successfully unblock. 

In [1] all counts are based on people that successfully unblock. In addition, all of the counts have a "or more" suffix, i.e, "1 or more", "2 or more". Since "1 or more invalid codes" is 25%, we know "0 invalid codes" is 75%. 75% of people __that successfully unblock__ are able to do so with their first unblock code, 25% of people __that successfully unblock__ require more than 1 unblock code. 25% leaves room for improvement, these users could probably be helped by a multi-use unblock code, or at least reduce friction. Sure, they signed in still, but they had to go through hoops to do so. Maybe those hoops are driving other people away (see below). Maybe 25% isn't that bad.

I wanted to know how many people never unblock themselves, and how many invalid unblock codes they send. I created a new set of charts [2]. Prepare to zoom-out, there's a lot of graphs there.

Between 40 and 45 % of blocked flows never successfully unblock. I found this curious and wanted to know how many unblock codes these people sent, and how many invalid unblock codes they entered.

75-80% of people who never unblock only send 1 code.
14-15% (fairly constant) of people who never unblock send 2 codes.
The rest are pretty insignificant.

Some possibilities for the composition of users who send 1 code:  1) attackers, 2) don't care enough to unblock, 3) don't receive the unblock code, 4) enter in the unblock code incorrectly and give up.

We can probably help 2 and 3 a bit. For 2 we know they have an account already, we just have to convince them to connect. 3 we are working on by tackling email deliverability.

The group of people who send 2 codes and still don't successfully unblock I find interesting. 14-15% of people manage to send 2 unblock codes. This group can be broken into at least two smaller groups: 1) users who click "Send another" on the first unblock screen, 2) users who entered an incorrect password, were blocked, entered the unblock code, entered a different password, were blocked again, and gave up.

@philbooth said we don't have flow event metrics on users who enter in an incorrect password, so we can't graph how frequently that occurs.

In the most optimistic case, assuming _all_ users are in the 2nd bucket, and assuming all of those users eventually type in the correct password and unblock code, we could remove the friction causing several hundred people a day to drop after sending 2 unblock codes - see the graph labelled `# unconfirmed after X sent codes`. That's a lot of assumptions. I've been dumpster diving enough today.

[1] - https://sql.telemetry.mozilla.org/queries/1958#3631
[2] - https://sql.telemetry.mozilla.org/queries/2161#3999

**Comment by philbooth** [comment] 2017-01-18 14:26
> ...we don't have flow event metrics on users who enter in an incorrect password...

We'll start receiving these events with the deployment of train 78 though. Incorrect passwords will show up as `route./account/login.400.103` events.

**Comment by vladikoff** [comment] 2017-01-24 19:58
from mtg: We need to check the data from new error metrics≥...

**Comment by vladikoff** [comment] 2017-01-26 20:15
from product meeting: closing this, metrics are fine... let's revisit this later.

**Closed** 2017-01-26 20:15 UTC
Labels: waffle:active

**Comment by shane-tomlinson** [comment] 2017-01-27 11:05
> metrics are fine

Is there a link to an updated chart?

**Comment by davismtl** [comment] 2017-01-27 21:11
> Is there a link to an updated chart?

It was not so much "because metrics fine" as it was I think we need to revisit this all together before we increase limit. We should also review this within the context of also increasing failed login limit which is very strict right now.
